### some variables ####################################################
SRCDIR = ~/projects/pipeline/ppln
JAVA = /mnt/xfs1/home/ifisk/java/jdk1.8.0_11/bin/java
GAPS = zzz #/mnt/scratch/asalomatov/data/hg19/gap_corr23.bed
BCBIODIR = /mnt/xfs1/bioinfoCentos7/software/installs/bcbio_nextgen/150617
TOOLSDIR = /mnt/xfs1/home/asalomatov/projects/dnanexus/installs
#PICARDDIR = $(BCBIODIR)/share/java/picard-1.96
PICARDDIR = /bioinfo/software/installs/picard/git # $(TOOLSDIR)/bin/picard
PICARD = $(TOOLSDIR)/bin/picard
#GENOMEREF = $(TOOLSDIR)/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
#GENOMEREF = $(TOOLSDIR)/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
GENOMEREF = /mnt/xfs1/scratch/asalomatov/data/b38/genome.fa
#GATK = /mnt/xfs1/bioinfo/software/builds/GATK/fromGitZip150607/gatk-protected-master/target/executable/GenomeAnalysisTK.jar
GATK = /mnt/xfs1/bioinfoCentos7/software/installs/GATK/3.6/GenomeAnalysisTK.jar
DBSNP = /mnt/xfs1/scratch/asalomatov/data/b38/variation/dbsnp144.b38.vcf.gz
BEDTLSDIR = $(TOOLSDIR)/bin
SAMTOOLS = $(TOOLSDIR)/bin/samtools
FREEBAYES = $(BCBIODIR)/bin/freebayes
#PLATYPUS = /mnt/xfs1/scratch/asalomatov/software/installs/bin/Platypus.py
PLATYPUS = $(TOOLSDIR)/bin/platypus
VCFLIBDIR = $(TOOLSDIR)/bin
#VCFLIBDIR = /bioinfo/software/installs/bcbio/bin
BGZIP = $(TOOLSDIR)/bin/bgzip
BCFTOOLS = $(TOOLSDIR)/bin/bcftools
BEDOPSDIR = /mnt/xfs1/bioinfo/software/builds/bedops/git/bedops/bin
SAMBAMBA = $(TOOLSDIR)/bin/sambamba
TABIX = $(TOOLSDIR)/bin/tabix
HAPMAP = /mnt/xfs1/scratch/asalomatov/data/b38/variation/hapmap_3.3.b38.vcf.gz
OMNI = /mnt/xfs1/scratch/asalomatov/data/b38/variation/1000G_omni2.5.b38.vcf.gz
SNP1000G = /mnt/xfs1/scratch/asalomatov/data/b38/variation/1000G_phase3.snps.high_confidence.b38.vcf.gz
INDEL1000G = /mnt/xfs1/scratch/asalomatov/data/b38/variation/1000G_phase3.indels.b38.vcf.gz
MILLSINDEL = /mnt/xfs1/scratch/asalomatov/data/b38/variation/Mills_and_1000G_gold_standard.indels.b38.vcf.gz
SNPEFFJAR = $(BCBIODIR)/Cellar/snpeff/4.1g/libexec/snpEff.jar 
SNPSIFTJAR = $(BCBIODIR)/Cellar/snpeff/4.1g/libexec/SnpSift.jar
SNPEFFCONF = /mnt/xfs1/scratch/asalomatov/data/snpEff/snpEff.config
SNPEFFGENOME = GRCh38.76
#DBNSFP = /mnt/scratch/asalomatov/data/dbNSFP/hg19/dbNSFP3.0_hg19_sorted.txt.gz
#DBNSFP = /mnt/xfs1/scratch/asalomatov/data/dbNSFP/dbNSFPv3.2a/dbNSFP3.2a.txt.gz
DBNSFP = /mnt/xfs1/scratch/asalomatov/data/dbNSFP/dbNSFPv3.3a/dbNSFPv3.3a.txt.gz
DBSPIDEX = /mnt/xfs1/scratch/asalomatov/data/spidex/spidex_public_noncommercial_v1_0.vcf.gz
#BAM2SMPL = /mnt/xfs1/home/asalomatov/projects/VIP/info/bam2smpl.yml
#BAM2SMPL = /mnt/scratch/asalomatov/data/SPARK/info/baylor_bam2sp_descr.yml
BAM2SMPL = /mnt/ceph/users/asalomatov/regeneron_spark_pilot/info/bam2SPid.yml
REGIONSBED = /mnt/xfs1/scratch/asalomatov/data/b38/chr1-22-X-Y-M.bed
#######################################################################
#/mnt/xfs1/bioinfoCentos7/software/installs/bcbio_nextgen/150617/bin
